#!/usr/bin/env python3
"""
build_games.py — GGR catalog generator for Arch Linux WebTTY.

Reads the raw upstream game lists in tools/sources/ and emits two browser data
files at the repo root:

    games-data.js     window.GAME_DATA    — games that ship with cover art
    games-noicon.js   window.NOICON_GAMES — UGS name-tile games (no art)

Every relative launch/icon path is rewritten to an absolute raw.githack.com URL
against the games repository so the catalog renders identically no matter where
the shell itself is hosted (githack, a static host, or file://).

Entry format (kept identical to upstream so the site stays a drop-in):
    [source, launch_url, icon_url, display_name]

Usage:  python3 tools/build_games.py
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "tools", "sources")
GAMES_BASE = "https://raw.githack.com/lauraevan/greatestgreatest-revive/main/"

# matches ["a","b","c","d"] tuples, tolerating escaped quotes inside strings
ENTRY_RE = re.compile(
    r'\[\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*,'
    r'\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"'
)


def absolute(path: str) -> str:
    """Rewrite a repo-relative path to an absolute githack URL."""
    path = path.strip()
    if not path:
        return ""
    if path.startswith(("http://", "https://", "//", "data:")):
        return path
    return GAMES_BASE + path.lstrip("./")


def parse(src_file: str):
    with open(src_file, encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    rows = []
    for source, launch, icon, name in ENTRY_RE.findall(text):
        rows.append([source.strip(), absolute(launch), absolute(icon), name])
    return rows


def dedupe(rows):
    """Drop exact duplicate launch targets, keep first occurrence + order."""
    seen, out = set(), []
    for r in rows:
        key = r[1]
        if key and key in seen:
            continue
        seen.add(key)
        out.append(r)
    return out


def emit(rows, var, out_file, note):
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    header = (
        "/* Generated by tools/build_games.py — do not edit by hand.\n"
        " * %s\n"
        " * Format: [source, launch_url, icon_url, display_name]\n"
        " */\n"
    ) % note
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write(header + "window.%s = [\n%s\n];\n" % (var, body))


def main():
    data = dedupe(parse(os.path.join(SRC, "games-data.src.js")))
    ugs = dedupe(parse(os.path.join(SRC, "games-noicon.src.js")))
    with_icon = sum(1 for r in data if r[2])

    emit(data, "GAME_DATA", os.path.join(REPO, "games-data.js"),
         "%d games with cover art." % len(data))
    emit(ugs, "NOICON_GAMES", os.path.join(REPO, "games-noicon.js"),
         "%d UGS name-tile games." % len(ugs))

    print("games-data.js   : %5d games (%d with icons)" % (len(data), with_icon))
    print("games-noicon.js : %5d UGS games" % len(ugs))
    print("total catalog   : %5d entries" % (len(data) + len(ugs)))
    if with_icon != len(data):
        print("warning: %d GAME_DATA rows have no icon" % (len(data) - with_icon),
              file=sys.stderr)


if __name__ == "__main__":
    main()
